import type { Metadata } from 'next';
import './globals.css';
import { Inter, Noto_Serif } from 'next/font/google';
import { cn } from '@/lib/utils';
import { TooltipProvider } from '@/components/ui/tooltip';
import { ThemeProvider } from 'next-themes';
import { Providers } from '@/components/providers';
import AppHeader from '@/app/(infrastructure)/components/AppHeader';

const notoSerif = Noto_Serif({ subsets: ['latin'], variable: '--font-serif' });

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        'font-sans',
        inter.variable,
        'font-serif',
        notoSerif.variable,
      )}
    >
      <body className="h-dvh flex flex-col">
        <TooltipProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
              <AppHeader />
              <main className="flex-1 flex">{children}</main>
            </Providers>
          </ThemeProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
